FROM php:7.1.7-apache

COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod rewrite

ADD check_release_repos.php /var/www/html/

RUN /usr/local/bin/docker-php-ext-install pdo pdo_mysql
RUN /usr/local/bin/docker-php-ext-enable pdo pdo_mysql

RUN apt update
RUN apt install -y cron

COPY releases-cron /etc/cron.d/
RUN crontab /etc/cron.d/releases-cron

CMD ["cron", "-f"]



